### PR TITLE
Fix file function constness

### PR DESCRIPTION
**Pull request by xezon**
Adds `const` to File member functions, but not yet the virtual functions.

### CODE REVIEW

**Review by feliwir — APPROVED** [review]

**Review by feliwir — APPROVED** [review]

**Comment by xezon** [comment]
Looks like your approval is yet non consequential :D

**Comment by feliwir** [comment]
> Looks like your approval is yet non consequential :D

i thought approving twice can't hurt :) It asked me to add my review again:
image

**Comment by jonwil** [comment]
I have evidence that these were not const in the original. Is there a reason to deviate from that?

**Comment by xezon** [comment]
Yes. const correctness is important.

**Comment by xezon** [comment]
To elaborate on const correctness, here is article:
https://isocpp.org/wiki/faq/const-correctness

In a nutshell, anything that is meant to be immutable should be marked `const`, most importantly on

* immutable global variables
* immutable public struct members
* immutable private class members
* immutable member functions, that promise to not change state of callee
* immutable function arguments

`const` does not change the runtime.

**Pull request merged**
