### PR TITLE
Updates GameMath version used.

### LINKED ISSUE #864: Need to add fast math functions
There are many places in our code where we call into slow deterministic gm_xxxx functions from GameMath but that don't need to be deterministic. We should add faster versions of Max, Min, Pow, Cos, Sin, Sqrt, Acos, Asin, Atan, Atan2, Tan, Ceil, Floor, Fast_To_Int_Floor, Fast_To_Int_Ceil, Fast_To_Int_Truncate, Fast_Float_Floor, Fast_Float_Ceil and Lrintf and use those in places where we are confident that the results are not going to be sent over the network or stored in any files (save games, replays, maps etc)

### PR DESCRIPTION
**Pull request by OmniBlade**
* Fixes #864

GameMath has been updated to make use of CPU instructions in some functions.

### CODE REVIEW

**Comment by feliwir** [comment]
Could be maybe merge #867 before, so we can see the perf change?

**Review by jonwil — APPROVED** [review]
Looks OK to me.

**Comment by xezon** [comment]
Related change: https://github.com/TheAssemblyArmada/GameMath/commit/4d2d8150717f4fa9dc429f8227c81a454ec2ffc6

**Review by xezon — APPROVED** [review]
Tested in RelWithDebInfo. Works. Performance is through the roof. On my machine it now runs with 300 FPS where it ran with 50 FPS prior this fix.

Fixes #864.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
