### PR TITLE
Major Readme improvements

### PR DESCRIPTION
**Pull request by mrtnptrs**
Especially the building instructions need improvements in the feature. Also it would be nice if we could provide a downloadable link to the game.dat file for TUC and TFD owners. What do you think of these improvements @OmniBlade ?

### CODE REVIEW

**Comment by OmniBlade** [comment]
Few things, first, the "build Thyme yourself" link points to the AV false positive warning, not the build section, not sure if that is intentional. Second, the AV warning itself should probably suggest to inspect and compile the project themselves to prove its a false positive?

**Comment by mrtnptrs** [comment]
Please, only merge this after considering #12 as the readme needs to be edited for that.

**Comment by mrtnptrs** [comment]
Could someone please check for grammar mistakes? (as I'm good at English, but it still isn't my native language)

**Comment by OmniBlade** [comment]
Okay, we'll give a Discord channel a whirl and see how it goes. You can add https://discord.gg/YhdMbvD to the readme.

**Comment by OmniBlade** [comment]
Grammar is a bit off in that latest addition, it would read better as something like:
"You can chat and discuss the development of Thyme on our [Discord channel](https://discord.gg/YhdMbvD) or on freenode in the #thyme channel."

**Pull request merged**
