### PR TITLE
Fixes AI not working correctly.

### PR DESCRIPTION
**Pull request by OmniBlade**
Fixes bug in the Thyme implementation of the games scripting code.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Is this fixing #100?

**Comment by OmniBlade** [comment]
> 
> 
> Is this fixing #100?

It is :D, had an `if` that was `==` instead of `!=`.

**Comment by duncanspumpkin** [comment]
Excellent. I spent ages trying to work out the source of the issue but didn't know enough to crack it. 

Btw you probably know this but if you add "Fix: #isuuenumber" then GitHub will auto close the referenced issue when the pr is merged. There a could other keywords that do it as well. I find it useful to avoid additional clean up work.

**Comment by OmniBlade** [comment]
The second commit already has `Fixes #issuenumber` in its message which does the same thing, not sure whether its best practice to put it in the commit message or the PR description though. Probably the PR now that I think about it since its specific to the repository.

**Pull request merged**
