### PR TITLE
Fix weather & weapon parsing

### PR DESCRIPTION
**Pull request by feliwir**

### CODE REVIEW

**Review by xezon — APPROVED** [review]
Squash and Merge.

**Review by jonwil — CHANGES_REQUESTED** [review]
The weather parsing can't be turned on yet because of missing SnowManager bits. See the TODO in WeatherSetting::Parse_Weather_Definition.

**Comment by feliwir** [comment]
> The weather parsing can't be turned on yet because of missing SnowManager bits. See the TODO in WeatherSetting::Parse_Weather_Definition.

Updated

**Review by jonwil — APPROVED** [review]
Looks good to me. Approved.

**Pull request merged**
