### PR TITLE
Add string type aliases

### PR DESCRIPTION
**Pull request by xezon**
See commits for individual changes.

### CODE REVIEW

**Review by jonwil — COMMENTED** [review]
Why did you remove the GAME_DEBUG_STRUCTS bits? Are they not actually present in the original WB binary? (which is what GAME_DEBUG_STRUCTS is for)

**Comment by tomsons26** [comment]
> Why did you remove the GAME_DEBUG_STRUCTS bits? Are they not actually present in the original WB binary? (which is what GAME_DEBUG_STRUCTS is for)

they are and WB will crash without them

**Review by tomsons26 — DISMISSED** [review]
Restore debug code

**Comment by xezon** [comment]
Restored GAME_DEBUG stuff.

**Review by OmniBlade — APPROVED** [review]

**Pull request merged**
