### PR TITLE
Fixes build error for newer ffmpeg versions

### PR DESCRIPTION
**Pull request by feliwir**
Enforces const correctness and avoid deprecated members

### CODE REVIEW

**Comment by feliwir** [comment]
This only seems to work for FFmpeg 5.0 and great. Will add a version check later

**Review by xezon — APPROVED** [review]

**Review by xezon — APPROVED** [review]

**Comment by xezon** [comment]
2 targets did not build. probably because old ubuntu was removed, but is still required?

**Comment by feliwir** [comment]
> 2 targets did not build. probably because old ubuntu was removed, but is still required?

yes, i removed those. I guess it's because the "develop" branch still has it

**Comment by feliwir** [comment]
Can this please get merged? It's really causing me a lot of headache under linux - i need to manually apply this fix on each branch i work on

**Comment by xezon** [comment]
It cannot be merged, because 2 checks do not trigger here.

**Comment by feliwir** [comment]
> It cannot be merged, because 2 checks do not trigger here.

I removed those 2 checks. They will never trigger

**Pull request merged**
