### PR TITLE
Fix compile warning in w3ddisplay from deprecated GetVersionEx function

### PR DESCRIPTION
**Pull request by xezon**

### CODE REVIEW

**Comment by jonwil** [comment]
Given that VER_PLATFORM_WIN32_WINDOWS means "Windows 9x" (at least according to available documentation) maybe its better to just remove the check entirely (given that we don't even run on Windows 9x)

**Comment by xezon** [comment]
Yes that is what was done within the ifdef block. I could delete the code if so desired, but I left it for now for documentation sake.

**Comment by jonwil** [comment]
No, I meant removing the whole lot including the W3D::Invalidate_Textures call (since that call is inside the "if version == Windows 9x" block)

**Comment by xezon** [comment]
Hmm. Why do you think that is an appropriate action? Not invalidating textures on Device Reset will likely cause Direct X to not be able to recover.

**Comment by jonwil** [comment]
The original game code is not calling Invalidate_Textures on modern windows so why do we need to do that?

**Comment by xezon** [comment]
I will take a look later.

**Comment by jonwil** [comment]
Its basically impossible for VersionInformation.dwPlatformId == VER_PLATFORM_WIN32_WINDOWS to be true on any version of Windows Thyme supports.

**Comment by duncanspumpkin** [comment]
We already use git for source control we have absolutely no need to add unusable code branches. Just delete the code.

**Comment by xezon** [comment]
Maybe comment out the whole function for now and add a TODO to remove finally later if never used?

**Comment by duncanspumpkin** [comment]
Why, we have already investigated and concluded is not used. Have a comment that there used to be special win9x code if you want. If in the future you can always use git history to find the original code

**Comment by xezon** [comment]
I would just like the Compiler Warning gone. Removing the function entirely will likely make it forgotten, and if ever someone wants it back, he likely re-implements it. No one will remember to check GIT history and where in time.

**Comment by xezon** [comment]
Is this good to go? Review is very small so should not take long to review.

**Comment by duncanspumpkin** [comment]
I would still like to see the dead code removed as it has already been investigated and if anyone for some reason wanted to view the original they can use git to find it.

**Comment by xezon** [comment]
Endless discussions. I can't search Git like I can search in Visual Studio. If we can't move forward with this then we have to keep this compiler warning in the build.

**Comment by jonwil** [comment]
PR solved by disabling the code via "#if 0". Closing.

**Pull request closed without merging**
