### PR TITLE
Fix ThingTemplate initialization order and missing members

### PR DESCRIPTION
**Pull request by xezon**
While debugging I saw constructor of ThingTemplate is wild. Ordering is not correct. Also a pod members had no value initialization. So I just set some reasonable ones for them.

### CODE REVIEW

**Review by tomsons26 — CHANGES_REQUESTED** [review]
Don't change order, it matches existing binaries, its easier to cross reference then.
for missing members do this at end
```
    // BUGFIX Intialize all members
    m_buildable(0),
    m_assetScale(1.0f),
    m_displayColor(0xFFFFFFFF),
    m_editorSorting(0),
    m_isForbidden(false),
    m_armorCopiedFromDefault(false),
    m_weaponsCopiedFromDefault(false),
    m_isBridge(false)
```
since we are messing about with these files in header add a new line after `unsigned char m_crushableLevel;` so there's a gap between static and members

**Comment by duncanspumpkin** [comment]
In general it's more performant for the order to match the declaration order. Plus you get the benefit of making it easier to confirm if items are missing.

 I really think we are making it much harder on ourselves striving for similarity to the binary these latest bugs are further showing that written code is not being understood when written. Perhaps if people were focusing on understanding rather than trying to make identical this wouldn't occur.

**Comment by xezon** [comment]
Technically the order of initialization will always match the declaration order. So it will behave the same. I disagree that comparability with Decompiled is a strong argument to leave it in the wrong order. It should follow CPP guidelines and be properly written in the correct order.

This makes
a) Easier to review declaration and initialization
b) Easier to debug, because the debug position will follow initialization order and not jump all over the place when stepping into constructor
c) Avoid compiler warnings due wrong initialization order on some compilers

**Comment by duncanspumpkin** [comment]
> Technically the order of initialization will always match the declaration order. So it will behave the same.

Hmm the more you learn. I'm sure I read something that said the opposite of this but seems I was mistaken on looking into it again.

**Comment by xezon** [comment]
Done.

**Review by tomsons26 — APPROVED** [review]

**Pull request merged**
