### PR TITLE
Allow captnlog to log without printing file name if so desired

### PR DESCRIPTION
**Pull request by xezon**
I would like to use captnlog without printing file names in tool for cleaner text presentation.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
What would the use case for this be. Perhaps captainslog is inappropriate for your use case.

**Comment by xezon** [comment]
Yeah I was thinking about making my own log. The lack of custom colors is for example also a problem.

**Comment by xezon** [comment]
I will implement this properly.

**Comment by xezon** [comment]
This Merge is superseeded by #412

**Pull request closed without merging**
